name = "DST Pack"
author = "studkid"
version = "ALPHA-0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b6928181a1a52cf430d318d87e6f453e6c00a89300455f9055ee2a699c4acf2"

[versions]
forge = "47.2.1"
minecraft = "1.20.1"
